vowels = set('aeeiouu')
print(vowels)
word = input('Provide a word to search for vowels ')
u = vowels.union(set(word))
print(u)
u_lst = sorted(list(u))
print(u_lst)
d = vowels.difference(set(word))
print(d)
i = vowels.intersection(set(word))
print(i)
